export const AI_CONSTANTS = {
    // Score generating base constants
    FEATURES: {
        COMPLETION_BONUS_CITY: 10,
        COMPLETION_BONUS_ROAD: 5,
    },
    NOOB: {
        SELF_WEIGHT: 0.1,
        OPPONENT_WEIGHT: 0.0,
        MEEPLE_PLACEMENT_BONUS: 3.0
    }
};

export const AI_CONSTANTS_EXPERIMENT = {
    MEEPLE_PLACEMENT: [3, 1.5, 1, 0.5, 0.5, 0.5, 0.5],
    EXTRA_POINT_ONE_SIDE_CITY_PLAYER: 0.5,
    EXTRA_POINT_ONE_SIDE_CITY_NEUTRAL: 1,
    FIELD_MULTIPLIER: 3,

    EASY: {
        SCORE_GAIN: 1,
        CITY_IN_PROGRESS: 0.8,
        ROAD_IN_PROGRESS: 0.5,
        MONASTERY_IN_PROGRESS: 0.6,
        FIELD: 0.25,
        MEEPLE_USAGE: 1,
        CITY_ATTACK: 0.2,
        ROAD_ATTACK: 0.1,
        FIELD_ATTACK: 0.05,

        OPPONENT_SCORE_GAIN: -1,
        OPPONENT_CITY_IN_PROGRESS: -0.8,
        OPPONENT_ROAD_IN_PROGRESS: -0.5,
        OPPONENT_MONASTERY_IN_PROGRESS: -0.6,
        OPPONENT_FIELD: -0.25,
        OPPONENT_MEEPLE_USAGE: -1,
        OPPONENT_CITY_ATTACK: -0.2,
        OPPONENT_ROAD_ATTACK: -0.1,
        OPPONENT_FIELD_ATTACK: -0.05,

        NEUTRAL_CITY_IN_PROGRESS: -0.5,
        NEUTRAL_ROAD_IN_PROGRESS: -0.1,
        NEUTRAL_FIELD: 0,
    },

    MEDIUM: {
        SCORE_GAIN: 1,
        CITY_IN_PROGRESS: 0.8,
        ROAD_IN_PROGRESS: 0.5,
        MONASTERY_IN_PROGRESS: 0.6,
        FIELD: 0.25,
        MEEPLE_USAGE: 1,
        CITY_ATTACK: 0.3,
        ROAD_ATTACK: 0.1,
        FIELD_ATTACK: 0.05,

        OPPONENT_SCORE_GAIN: -1,
        OPPONENT_CITY_IN_PROGRESS: -0.8,
        OPPONENT_ROAD_IN_PROGRESS: -0.5,
        OPPONENT_MONASTERY_IN_PROGRESS: -0.6,
        OPPONENT_FIELD: -0.25,
        OPPONENT_MEEPLE_USAGE: -1,
        OPPONENT_CITY_ATTACK: -0.3,
        OPPONENT_ROAD_ATTACK: -0.1,
        OPPONENT_FIELD_ATTACK: -0.05,

        NEUTRAL_CITY_IN_PROGRESS: -0.5,
        NEUTRAL_ROAD_IN_PROGRESS: -0.1,
        NEUTRAL_FIELD: 0,
    }

    // MEDIUM: {
    //     SCORE_GAIN: 1,
    //     CITY_IN_PROGRESS: 0.8,
    //     ROAD_IN_PROGRESS: 0.4,
    //     MONASTERY_IN_PROGRESS: 0.5,
    //     FIELD: 0.25,
    //     MEEPLE_USAGE: 1,
    //     CITY_ATTACK: 0.4,
    //     ROAD_ATTACK: 0.15,
    //     FIELD_ATTACK: 0.1,
    //
    //     OPPONENT_SCORE_GAIN: -1,
    //     OPPONENT_CITY_IN_PROGRESS: -0.8,
    //     OPPONENT_ROAD_IN_PROGRESS: -0.4,
    //     OPPONENT_MONASTERY_IN_PROGRESS: -0.5,
    //     OPPONENT_FIELD: -0.25,
    //     OPPONENT_MEEPLE_USAGE: -1,
    //     OPPONENT_CITY_ATTACK: -0.4,
    //     OPPONENT_ROAD_ATTACK: -0.15,
    //     OPPONENT_FIELD_ATTACK: -0.1,
    //
    //     NEUTRAL_CITY_IN_PROGRESS: -0.5,
    //     NEUTRAL_ROAD_IN_PROGRESS: -0.1,
    //     NEUTRAL_FIELD: 0,
    // }
}
